index.js, src/Analysis.js, src/constants.js, src/obfuscators/index.js, src/obfuscators/trojan-source.js, test/fixtures/obfuscated/unsafe-unicode-chars.js, test/obfuscated.spec.js
Fixes #15 
Standard implementation of the trojan source detection using a list of dangerous Unicode control characters (see more here : [https://www.unicode.org/reports/tr9/](url)).
For now, a warning is collected whenever one of the unsafe control char is found in a source string. Here is an example of the collected warning : 
`{
kind: 'obfuscated-code',
location: [ [ 0, 0 ], [ 0, 0 ] ],
value: 'trojan-source'
}`
The analysis is done directly in a brand new Analysis class method `analyzeSourceString()` that could be used for all checks upstream the Tree walk requiring the whole source string.
=> feat: add trojan source detection

README.md, index.d.ts, index.js, package-lock.json
Issue #26 
We add a new severity property for each warning:
- Information (For things not related to security, with valid values or a lot of false positive).
- Warning (the default).
- Critical (Implies malicious code or intent).
=> feat(warnings): add new severity property to warnings 

src/probes/isArrayExpression.js, src/probes/isAssignmentExpression.js, src/probes/isBinaryExpression.js, src/probes/isFunctionDeclaration.js, src/probes/isImportDeclaration.js, src/probes/isLiteral.js, src/probes/isLiteralRegex.js, src/probes/isObjectExpression.js, src/probes/isRegexObject.js, src/probes/isUnaryExpression.js, src/probes/isUnsafeCallee.js
Add few JSDoc and comments to probes (to help a bit new contributors).
=> chore: add few jsdoc to probes (with links to estree and code examples)

index.js, test/module.spec.js, test/regress.spec.js
Always support parsing of ESM even if `module` false is provided to JS-X-Ray.
=> refactor: enhance parseScript to always support ESM

README.md, docs/shady-link.md, src/probes/isLiteral.js, src/warnings.js, test/probes/isLiteral.spec.js, types/warnings.d.ts
=> feat: add shady-link warning

README.md, index.js, src/utils.js, test/fixtures/regress/html-comments.js, test/regress.spec.js, test/utils.spec.js, types/api.d.ts
Add a new option `removeHTMLComments` to remove any HTML comment from the provided source (or file).
Adding this as an option disabled by default because I'm not quite sure of the impact of this (and if this could be exploited in someway).
Should fixes #109
=> feat: add removeHTMLComments option

src/Analysis.js, src/obfuscators/index.js, test/fixtures/obfuscated/notMorse.js, test/obfuscated.spec.js
This PR fixes #144 
The stringCharDiversity was breaking the test (and the analysis), in the `morse.js` fixture, we have somethings like:
- `’.-‘: ‘a’,` -> here, stringCharDiversity is 2 
- `’-…’: ‘b’,` -> stringCharDiversity is 2 
- `’-.-.’: ‘c’,` -> stringCharDiversity is 2 
- `’-..’: ‘d’,` ->stringCharDiversity is 2 
-  `’.’: ‘e’,` ->  stringCharDiversity is 1
- `’..-.’: ‘f’,` -> stringCharDiversity is 2 
- etc  
Actually  the total counter of morseLiteral in the `morse.js` fixture is **37**, which match: 
```js
else if (analysis.counter.morseLiteral >= 36) {
encoderName = "morse";
}
```
That’s why I think this fix is fine.
I’ve also added a "not morse" detection test, I’m not sure about this test plus-value and the fixture’s accuracy but it should test there is no abuse with theses …
=> fix: broken morse detection

src/warnings.js, test/warnings.spec.js, types/warnings.d.ts
The purpose of this PR is to resolve #159 
close #159
=> Add a source property to Warnings

index.js, test/illegalReturnStatement.spec.js
=> fix: illegal return statement parsing error

README.md
this PR fix the example in readme to prevent "location" field displays wrong way when running as script with Node.js. (nested displayed as [Array])  
Since this repo doesn't have a "dev" branch and i don't have permission to this repo to push more branches, this PR directly pointed to master/main branch. If i need to change it, feel free to ask me to do so.  
Thx
=> fix the example in readme to prevent "location" field displays wrong way when running as script with Node.js. (nested displayed as [Array])

README.md
=> docs: estree-ast-utils typo

src/probes/isRequire.js, test/issues/177-wrongUnsafeRequire.spec.js, test/issues/179-UnsafeEvalRequire.spec.js
=> fix(isRequire): do not resolve CallExpr

src/ProbeRunner.js, test/ProbeRunner.spec.js
// TODO: https://github.com/NodeSecure/js-x-ray/blob/master/src/ProbeRunner.js#L74
Purpose of this PR is to : 
Note that i have used `import assert from "node:assert";` in probeRunner class but same can be done using if conditional.
LMK if it seems ok and enough to cover this TODO in probeRunner class ? I can assert that name exist as well ?
If anyone want to participate/feedback/propose/improve solution don't hesitate!
=> feat(probeRunner): assert probes method in proberunner

src/probes/isRequire.js, test/issues/178-path-join-literal-args-is-not-unsafe.spec.js
This PR addresses partially issue [ #178](https://github.com/NodeSecure/js-x-ray/issues/178).
If `path.join` is called in `require` and every argument is a string literal:
```js
const bin = require(path.join('.', 'bin.js'))
```
The dependency is normalized an no unsafe-import warning is triggered.
=> build path.join called in require if args are string literals

src/probes/isUnsafeCallee.js, test/issues/180-logicalexpr-return-this.spec.js, test/probes/isUnsafeCallee.spec.js, workspaces/estree-ast-utils/README.md, workspaces/estree-ast-utils/src/extractLogicalExpression.js, workspaces/estree-ast-utils/src/index.d.ts, workspaces/estree-ast-utils/src/index.js, workspaces/estree-ast-utils/src/utils/VariableTracer.js, workspaces/estree-ast-utils/test/VariableTracer/assignments.spec.js, workspaces/estree-ast-utils/test/extractLogicalExpression.spec.js
close #180 
Still need to implement better tracing support
=> refactor: consider Function("return this") as safe

src/ProbeRunner.js, src/probes/isRequire/RequireCallExpressionWalker.js, src/probes/isRequire/isRequire.js, test/probes/isRequire.spec.js
This PR addresses issue [#220](https://github.com/NodeSecure/js-x-ray/issues/220).
=> Refactor isRequire probe with new class RequireCallExpressionWalker

src/AstAnalyser.js, test/AstAnalyser.spec.js, types/api.d.ts
Issue #223 
It was suspiciously easy, let me know if there are any issues :)
=> Use JsSourceParser as default parser for AstAnalyser class

workspaces/estree-ast-utils/LICENSE, workspaces/sec-literal/LICENSE, workspaces/sec-literal/package.json, workspaces/sec-literal/test/hex.spec.js, workspaces/sec-literal/test/literal.spec.js, workspaces/sec-literal/test/patterns.spec.js, workspaces/sec-literal/test/utils.spec.js
=> refactor(sec-literal/test): use the Node.js native test runner

docs/shady-link.md, src/probes/isLiteral.js, test/probes/isLiteral.spec.js
resolve https://github.com/NodeSecure/js-x-ray/pull/260
=> add shady link regex for check url with ips

README.md, docs/api/AstAnalyser.md, src/AstAnalyser.js, test/AstAnalyser.spec.js, types/api.d.ts
Fixes #268
Signed-off-by: Tony Gorez <gorez.tony@gmail.com>
=> feat: add intialize and finalize for AstAnalyser.analyze API

index.js
These warnings are added to inform users that these APIs will be removed in v8 and encourage them to use `AstAnalyser` instead.
Fixes #266
=> Added deprecation warnings for `runASTAnalysis` and `runASTAnalysisOn`

src/Deobfuscator.js, test/issues/295-deobfuscator-function-declaration-id-null.spec.js
=> fix(Deobfuscator): return if Node is null in extractCounterIdentifiers

src/ProbeRunner.js, src/probes/isESMExport.js, test/EntryFilesAnalyser.spec.js, test/fixtures/entryFiles/export.js, test/probes/isESMExport.spec.js
=> fix: implement isESMExport probe to consider export stmts as dependencies

src/probes/isLiteral.js
According to [Node.js deprecation notice DEP0191](https://nodejs.org/api/deprecations.html#dep0191-replbuiltinmodules), the `repl.builtinModules` property is deprecated as of Node.js v24.0.0:
> The `node:repl` module exports a `builtinModules` property that contains an array of built-in modules. This was incomplete and matched the already deprecated `repl._builtinLibs` (DEP0142) instead it's better to rely upon `require('node:module').builtinModules`.
- Changed import from `import { builtinModules } from "repl";` to `import { builtinModules } from "module";`
=> fix: change builtinModules import from repl to module

docs/api/EntryFilesAnalyser.md, src/EntryFilesAnalyser.js, test/EntryFilesAnalyser.spec.js, types/api.d.ts
=> feat(EntryFilesAnalyzer): add option to ignore entry file that doesn't exist

test/AstAnalyser.spec.js
1. **`should include flags property in response`** - Ensures flags property exists and prevents regression where it was forgotten
2. **`should add is-minified flag for minified files`** - Tests minified content detection and flag setting  
3. **`should add oneline-require flag for one-line exports`** - Tests one-line require exports and flag mutual exclusion
- Flags property existence
- "is-minified" flag functionality  
- "oneline-require" flag functionality
- Flag mutual exclusion logic
=> test(AstAnalyser): add tests for flags property and minified/oneline-require detection

.changeset/four-bars-bet.md, workspaces/js-x-ray/docs/AstAnalyser.md, workspaces/js-x-ray/src/ProbeRunner.js, workspaces/js-x-ray/src/SourceFile.js, workspaces/js-x-ray/src/probes/isSyncIO.js, workspaces/js-x-ray/src/probes/isWeakCrypto.js, workspaces/js-x-ray/src/types/api.d.ts, workspaces/js-x-ray/test/ProbeRunner.spec.js
=> feat(probes): add initialize
